


server:
  port: 5006
spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true
    username: root
    password: topik712
    driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa.show-sql: true

stripe:
  api:
    key: "your stripe api key"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

payment:
  frontend:
    success-url: "http://localhost:3000/payment-success"
    cancel-url: "http://localhost:3000/payment/cancel"