services:

  # DB config for userdb
  userdb:
    image: mysql
    container_name: userdb
    restart: unless-stopped
    ports:
      - 3301:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 60s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    networks:
      - devsaif


  # DB config for booking
  bookingdb:
    image: mysql
    container_name: bookingdb
    restart: unless-stopped
    ports:
      - 3302:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 60s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookingdb
    networks:
      - devsaif

  # DB config for category
  categorydb:
    image: mysql
    container_name: categorydb
    restart: unless-stopped
    ports:
      - 3303:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 60s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: categorydb
    networks:
      - devsaif

  # DB config for payment
  paymentdb:
    image: mysql
    container_name: paymentdb
    restart: unless-stopped
    ports:
      - 3304:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 60s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paymentdb
    networks:
      - devsaif

  # DB config for salon
  salondb:
    image: mysql
    container_name: salondb
    restart: unless-stopped
    ports:
      - 3305:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 60s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salondb
    networks:
      - devsaif


  # DB config for service-offering
  service-offeringdb:
    image: mysql
    container_name: service-offeringdb
    restart: unless-stopped
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 60s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service-offeringdb
    networks:
      - devsaif


  #eureka server configuration
  eurekaserver:
    image: "saifulaziz712/salon-eureka-server:v1"
    ports:
      - "8070:8070"
    container_name: eurekaserver
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - devsaif


  #user service configuration
  user:
    image: "saifulaziz712/salon-user:v1"
    ports:
      - "5001:5001"
    container_name: user
    restart: unless-stopped
    depends_on:
      userdb:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: "user-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://userdb:3306/userdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - devsaif


  #booking service configuration
  booking:
    image: "saifulaziz712/salon-booking:v1"
    ports:
      - "5005:5005"
    container_name: booking
    restart: unless-stopped
    depends_on:
      bookingdb:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: "booking-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://bookingdb:3306/bookingdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - devsaif


  #category service configuration
  category:
    image: "saifulaziz712/salon-category:v1"
    ports:
      - "5003:5003"
    container_name: category
    restart: unless-stopped
    depends_on:
      categorydb:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: "category-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://categorydb:3306/categorydb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - devsaif


  #payment service configuration
  payment:
    image: "saifulaziz712/salon-payment:v1"
    ports:
      - "5006:5006"
    container_name: payment
    restart: unless-stopped
    depends_on:
      paymentdb:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: "payment-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://paymentdb:3306/paymentdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - devsaif

  #salon service configuration
  salon:
    image: "saifulaziz712/salon:v1"
    ports:
      - "5002:5002"
    container_name: salon
    restart: unless-stopped
    depends_on:
      salondb:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: "salon-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://salondb:3306/salondb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - devsaif

  #service-offering service configuration
  service-offering:
    image: "saifulaziz712/salon-service-offering:v1"
    ports:
      - "5004:5004"
    container_name: service-offering
    restart: unless-stopped
    depends_on:
      service-offeringdb:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: "service-offering"
      SPRING_DATASOURCE_URL: "jdbc:mysql://service-offeringdb:3306/service-offeringdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - devsaif

  #gateway-server configuration
  gateway-server:
    image: "saifulaziz712/salon-gateway-server:v1"
    ports:
      - "5000:5000"
    container_name: gateway-server
    restart: unless-stopped
    depends_on:
      eurekaserver:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: "gateway-server"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - devsaif


networks:
  devsaif:
    driver: "bridge"
