
server:
  port: 5001
spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true
    username: root
    password: topik712
    driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa.show-sql: true